[Say] Allow modification of an existing bot message like many other bots
retke/Laggrons-Dumb-Cogs pull request #191
Opened 2021-12-30 16:32 UTC by AAA3A-AAA3A

Hello,
This code modification allows to modify an existing bot message.
This feature exists on many bots and has already been requested in the repo channel on Red's cogs server.
Thanks in advance.

2022-01-03 09:10 UTC, laggron42 requested changes
Hello and thanks for your pull request!

While I haven't planned myself to add this feature, I'm open to merge this PR. However, this is going to need a few changes before I accept this. Don't worry, you're on the right way!

## Add a command

I don't like how you're re-using the existing commands, adding an optional parameter.

* You have to specify the channel of the message, while the message link already gives that info
* I can see why you would want `sayd` and `sayad` to use the same features, but I don't believe it's necessary when it comes to editing the content of a message (plus you're not really using `sayad` given how your code is written).
* It's confusing.

Would be better imo to just add a `[p]editmsg` command for example.

## Misc

* Guess you can update the version number to 1.7.0 (can't comment on an unedited line)
* You can probably add a tag or change the description a bit in `info.json`
* Build is failing because of formatting, fix that with ``python3 -m black -l 99 --check --diff `git ls-files "*.py"` ``

----

Check the comment attached below for the other stuff. Of course if you don't agree with me, feel free to explain your view. And once again, thanks for this PR!

2022-01-03 09:10 UTC, laggron42 commented on say/say.py
> +            return
I don't know if it really makes sense to put this inside the `say` function, it could have its own new function which would make more sense.

Furthermore, this needs a try/except block. Even if all permissions are supposed to be correct, you never know what may happen afterwards. Wrap the call, inform the user, log the error, something like this:

```py
try:
    await message.edit(content=text, delete_after=delete, allowed_mentions=mentions)
except discord.HTTPException:
    # see what I did below
```
Take as example what I did with `channel.send`

2022-01-03 17:28 UTC, AAA3A-AAA3A commented
Thank you for your reply.
To start with, I need to get into the habit of running black and isort on them (so many parameters?) for the PR. I don't do it because I don't use them myself on my repo.
Secondly, I didn't do any try-except because I didn't know the possible errors, knowing that none of them seemed to match with the say possible command.
Also, the "sayad" command works with the edit and will allow the deletion of this same message.
I don't know how to retrieve a channel from an invitation, but anyway, the commands work with the id of the message only, no need for the channel.
Finally, I only included a toggle because I didn't want to add 3 commands to the cog, that's a lot.
I'm going to do the others modifications, but what do you think of the rest?
Thanks in advance for your answer.

2022-01-14 10:20 UTC, laggron42 commented
Hey, here are some details

> To start with, I need to get into the habit of running black and isort on them (so many parameters?) for the PR. I don't do it because I don't use them myself on my repo.

Just `pip3 install black`. If you're on Linux, WSL or macOS, just run `make reformat`. Else ``python3 -m black -l 99 `git ls-files "*.py"` ``. You can view the arguments in the `Makefile` of the repo.

> Secondly, I didn't do any try-except because I didn't know the possible errors, knowing that none of them seemed to match with the say possible command.

Most important ones are `discord.Forbidden` (not allowed to do x) and `discord.HTTPException` (any error code, `Forbidden` is a subclass of `HTTPException` anyway). Just catch the latter if you're unsure.

> Also, the "sayad" command works with the edit and will allow the deletion of this same message.
> Finally, I only included a toggle because I didn't want to add 3 commands to the cog, that's a lot.

I'm personally not sure if that's really necessary. I prefer simplicity and ease of use over complexity and confuseness. I know I made a lot of complex and confusing features in other cogs, but at least I'm not shoving them in commands that should stay simple and easy to use.

Make a new group command, add subcommands if you really want those features. Something like this maybe?

- `!editmsg <message link> <content>`
- `!editmsg delete <message link> <content>`
- `!editmsg autodelete|ad <message link> <content>`
- `!editmsg mention <message link> <content>`

> I don't know how to retrieve a channel from an invitation, but anyway, the commands work with the id of the message only, no need for the channel.

It's a [`discord.Message`](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message) object, you can get whatever you want from it, `message.channel` and `message.guild` for example. Don't hesitate to check the attributes.

----

Overall I like the addition, I just don't want it to be an addition to the existing commands and make the cog more confusing, when it should be the easiest to use.

2022-01-14 14:21 UTC, AAA3A-AAA3A commented
I finally made a separate command because there were problems with the normal commands taking the text as the message argument. I included the error messages, the try-except and the help menu. If you still agree, I will modify my PR a little later.
Perhaps an await ctx.tick() for all commands would be useful?

2022-01-14 14:38 UTC, AAA3A-AAA3A commented
The user can only put the message id instead of a link.
I agree to separate.
I recently understood this story of discord.py errors and the fact that one was a category containing the others.
Got it for the styling, but can't I just run `black .` and` isort .`?

2022-05-25 17:15 UTC, AAA3A-AAA3A commented
Hello,
I'm coming back to this PR which is more than 4 months old. Would you like a further modification of the code?
Thank you in advance.

2022-06-01 18:23 UTC, laggron42 commented
Just waiting for changes from your end to review again, which means separating commands and resolving other open conversations. Feel free to DM me if you have some quick questions about design.

Also it may be worth to base your PR on the `dpy2` branch, Say benefitted some updates there

2022-06-12 11:33 UTC, AAA3A-AAA3A commented
I am closing this PR and will open a new one as my clone does not have the new dpy2 branch.

2022-06-12 11:33 UTC, closed without merging